language: java
sudo: false
jdk:
- oraclejdk8
install:
- mvn --settings .ci/settings.xml install -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true
before_install:
- if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE
  --import; fi
- if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE
  --import-ownertrust; fi
after_success:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify jacoco:report
  coveralls:report -Dgpg.skip
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email:
  - marcos.hgb@gmail.com
  - matheus.ggoes@outlook.com
deploy:
- provider: script
  script: bash .ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    repo: marcosbarbero/spring-boot-starter-purge-accesslog
    jdk: oraclejdk8
