language: java
sudo: false
jdk:
- oraclejdk8
install:
- mvn --settings .ci/settings.xml install -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true
before_install:
- if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE
  --import; fi
- if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE
  --import-ownertrust; fi
after_success:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify jacoco:report
  coveralls:report -Dgpg.skip
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email:
  - marcos.hgb@gmail.com
  - matheus.ggoes@outlook.com
deploy:
- provider: script
  script: bash .ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    repo: marcosbarbero/spring-boot-starter-purge-accesslog
    jdk: oraclejdk8
env:
  global:
  - secure: lZ20Osne84Xw78/3aCk7q95rrxSMhq8Mys7AqYe58GgPbBrAA1zxUDpy59hebqBGnU1E0l6bUwhE74tpsLRKRUqqPhjBTJJCuXtvjm7J7ZtH5KmtJy3LRvPgWnojii/NOhMpRnGIzzTKm4+yLkUW0Hqqh5yaabMQnZ/f6jJi2HdWtdOcb3NYQo9Wbd9r3iaNrnkz5k8jCALIUFBUhS/CeIrTCPYKkRqBVnPZucQoIWX7gGySmM8oX4aTi+J55aFsRFVR8JA5qg4w/NwKFZqnYi51hbXQ1ocQzp8jf1aqPofdS50UEcMr8oiBIo32TbLruKwNWec5Ns9jKDv/UzIInvg5XqSAydGeumxXQQInJqgXxqEimtWpr/435S4Q1yuxwpjVG2sWY/1Hih+tKHmL++7cV3LlnEBPyAY3jEIPiNM9TLd5Bo+SGpDY3xf9kNt2zFAtwNkBhPUMPuJF3yFVCPpcL0AdfYGa+FSAet7gNrRU8XY5WKzctqAWpLn/G/hxAvOawS/rxx+2HKnGgui91uvUgPUI4ToZjupFQSNfeoTwiFGYwU/asBM7PpKk4rBtyQXy9zMVJiTKOw5yQnYBw+CZ1VuNucMXVFb7FRe0bgbOo2wo9+K0TMu+Mn1OpGT23LoWNXlUyXW0xYcuSr+3pZjh/AYXee1fDoa1qQ3pZp8=
  - secure: MPkHQhyeFHkg6qWtFve3gOSyJnOp13NPYXeKUsM6sDRaW8NRojdIt38M/me17pcGegxxB1zVrDhBWicV84UCiV1C6RPMGstod0Jw6+arjLMHIdioScskY/Zp0k69gX4Mzi1yP2OvbmHV6tMow1568KPTWDzXdvESWd57xrH59IaVnUT4Mj0aQAkrsyLafApZ3xAxXzVEUGZOpFv4WeHGpdnnoTo+Nxtu6risyVSF7mMl28sJ9PogLuybof+Kan0Raaw8xO4kVnTt56hudaL8OXv84RIh1zcfWMon+H1MSJUNk0zeYzua9Luv4hmQWqRVQt/8W3L3AWjaQwYSdBmB0l5TDRRZ5yP2G+7UMfq5K/KXZxyl3kxSC1ausj8jBgKNpANR1qCKHwiGZdJO3CRz7KITV+AS49TX88yhIFmssaxj2AbT6WX1OJVxf2QkQhsKpkNU7uE8gq3eDwEr7sTRt2mAi506AmTth4vP56VuOMpCqzZhC171m2jPMBZ2+pjCDHxlWEyMzEpu5SsZAzGOc7uBvuTZKmSKc+ylSC3aKgalWNSaKf/OqI/x7pCJa7sVhg82dWPE0yf6vP8we5Sg2KOi0BA/Kw8xpLs/y0nngN6lbbrDN+fVcHFvS/bS4dYmC1sVj+qC27hCNCrjvKl2hFBQI1//sXJLLF1yA9E78WM=
